// <auto-generated />
using System;
using Api.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.DataBase.Migrations.ApiContextMigrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20201019212911_DeleteFieldEntity")]
    partial class DeleteFieldEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Api.DataBase.DbEntities.FormDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Fields")
                        .HasColumnType("text");

                    b.Property<string[]>("Keywords")
                        .HasColumnName("keywords")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("forms");
                });
#pragma warning restore 612, 618
        }
    }
}
